services:
  zabbix-websocket-bridge:
    image: ghcr.io/voltkraft/zabbix-websocket-bridge:latest
    pull_policy: always
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      LOG_LEVEL: info
    ports:
      - "8080:8080"
    restart: unless-stopped
